server:
  port: 8080
spring:
  #配置静态资源目录
  #    allow-circular-references: true //允许循环引用
  resources:
    static-locations: ["file:/C:/Users/mzby/Desktop/Back_end/数据库大作业/数据库大作业/springboot_furn/springboot_furn/src/main/resources/static"]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: weibb
    password: 18907788073
    url: jdbc:mysql://8.135.237.176:3306/library?useUnicode=true&characterEncoding=utf-8&useSSL=true

#配置mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml #指定mapper.xml文件位置
  type-aliases-package: com.wei.furn.bean #实例类所在的包，这样通过类名可以直接引用
#mybatis-plus:
#  configuration:
#    #这里我们配置输出底层的sql，方便我们观察sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

